version: '3.8'

services:
  frontend:
    container_name: todo-list
    image: todo-list
    build:
      target: development
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
